name: CWOAC
url: https://www.codersoffortune.net
description: Solving problems with too much technology.
permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: rouge
theme: jekyll-theme-leap-day
